networks:
  temporal-network:
    driver: bridge
    name: temporal-network
    external: true

services:

  entity:
    image: temporal-entity-demo/user-entity:latest
    deploy:
      replicas: 5
    networks:
      - temporal-network
