networks:
  temporal-network:
    driver: bridge
    name: temporal-network

services:
  pulsar:
    image: apachepulsar/pulsar:latest
    container_name: pulsar
    command: /pulsar/bin/pulsar standalone
    volumes:
      - ./pulsar/init-pulsar.sh:/pulsar/init/init-pulsar.sh:ro  # Mount the script
#      - pulsar_data:/pulsar/data
#      - pulsar_conf:/pulsar/conf
    ports:
      - "6650:6650"
      - "8081:8080"
    healthcheck:
      test: curl --fail http://localhost:8080/admin/v2/clusters || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    post_start:
      - command: /pulsar/init/init-pulsar.sh
    environment:
      PULSAR_MEM: "-Xms256m -Xmx512m"
    networks:
      - temporal-network

#volumes:
# pulsar_data:
#  pulsar_conf:
