<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>ai.tensor7</groupId>
        <artifactId>entity-demo-parent-java</artifactId>
        <version>0.0.1</version>
    </parent>

    <artifactId>temporal-entity-demo-consumer</artifactId>
    <packaging>jar</packaging>

    <name>consumer</name>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>24</maven.compiler.source>
        <maven.compiler.target>24</maven.compiler.target>
        <akka.version>2.8.1</akka.version>
        <fabric8.maven.plugin.version>0.48.1</fabric8.maven.plugin.version>
        <protobuf-java.version>3.41</protobuf-java.version>
        <protobuf.version>4.34.1</protobuf.version>
        <protobuf-maven-plugin.version>5.1.3</protobuf-maven-plugin.version>
        <pulsar.version>4.0.10</pulsar.version>
        <temporal.sdk.version>1.35.0</temporal.sdk.version>
<!--    <logback.classic.version>1.5.32</logback.classic.version> NOTE: This is causing a problem w/ this Akka -->
        <logback.classic.version>1.2.13</logback.classic.version>
        <tests.skip>false</tests.skip>
        <!-- The Scala versions -->
        <scala.version>2.13.14</scala.version>
        <scala.binary.version>2.13</scala.binary.version>
<!--        <micrometer-registry-version>1.9.9</micrometer-registry-version>-->
        <micrometer-registry-version>1.16.5</micrometer-registry-version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.typesafe.akka</groupId>
            <artifactId>akka-actor-typed_${scala.binary.version}</artifactId>
            <version>${akka.version}</version>
        </dependency>
        <dependency>
            <groupId>com.typesafe.akka</groupId>
            <artifactId>akka-stream-typed_${scala.binary.version}</artifactId>
            <version>${akka.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.pulsar</groupId>
            <artifactId>pulsar-client</artifactId>
            <version>${pulsar.version}</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>${logback.classic.version}</version>
        </dependency>

        <dependency>
            <groupId>io.temporal</groupId>
            <artifactId>temporal-sdk</artifactId>
            <version>${temporal.sdk.version}</version>
        </dependency>

        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-prometheus</artifactId>
            <version>${micrometer-registry-version}</version>
        </dependency>

        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-commons</artifactId>
            <version>${micrometer-registry-version}</version>
        </dependency>

        <dependency>
            <groupId>ai.tensor7</groupId>
            <artifactId>temporal-user-entity-workflow</artifactId>
        </dependency>

        <!-- Build specific dependencies -->
        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
            <version>${protobuf.version}</version>
        </dependency>

        <!-- Test dependencies start here -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.9.1</version>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.5.5</version>
                <configuration>
                    <skipTests>${tests.skip}</skipTests>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>${maven.compiler.source}</source>
                    <target>${maven.compiler.target}</target>
                    <compilerArgs>
                        <arg>-Xlint:unchecked</arg>
                        <arg>-Xlint:deprecation</arg>
                        <arg>-parameters</arg>
                    </compilerArgs>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.6.3</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <!--suppress UnresolvedMavenProperty -->
                    <executable>java</executable>
                    <arguments>
                        <argument>-classpath</argument>
                        <!-- automatically creates the classpath using all project dependencies,
                             also adding the project build directory -->
                        <classpath/>
                        <argument>ai.tensor7.app.UserEventConsumer</argument>
                    </arguments>
                </configuration>
            </plugin>

            <!-- docker image creation -->
            <!-- https://github.com/fabric8io/docker-maven-plugin -->
            <!-- To generate docker image: mvn clean compile package docker:build -->
            <plugin>
                <groupId>io.fabric8</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <version>${fabric8.maven.plugin.version}</version>
                <configuration>
                    <verbose>true</verbose>
                    <useColor>true</useColor>
                    <images>
                        <image>
                            <name>temporal-entity-demo/consumer</name>
                            <build>
                                <from>docker.io/library/eclipse-temurin:24</from>
                                <tags>
                                    <tag>${project.version}</tag>
                                </tags>
                                <entryPoint>
                                    <exec>
                                        <arg>java</arg>
                                        <arg>-cp</arg>
                                        <arg>/maven/*</arg>
                                        <arg>ai.tensor7.app.UserEventConsumer</arg>
                                    </exec>
                                </entryPoint>
                                <assemblies>
                                    <assembly>
                                        <descriptorRef>artifact-with-dependencies</descriptorRef>
                                    </assembly>
                                </assemblies>
                            </build>
                        </image>
                    </images>
                </configuration>
                <executions>
                    <execution>
                        <id>build-docker-image</id>
                        <phase>package</phase>
                        <goals>
                            <goal>build</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <!-- END docker image creation -->

            <!-- BEGIN Protobuf Maven Plugin -->
            <!-- https://github.com/ascopes/protobuf-maven-plugin -->
            <!-- DOCS: https://ascopes.github.io/protobuf-maven-plugin/ -->

            <plugin>
                <groupId>io.github.ascopes</groupId>
                <artifactId>protobuf-maven-plugin</artifactId>
                <version>${protobuf-maven-plugin.version}</version>

                <configuration>
                    <protoc>${protobuf.version}</protoc>
                    <sourceDirectories>
                        <sourceDirectory>src/main/proto</sourceDirectory>
                    </sourceDirectories>

                </configuration>

                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <!-- END Protobuf Maven Plugin -->
        </plugins>
    </build>
</project>
