app {
  pulsar-host = "localhost"
  pulsar-host = ${?PULSAR_HOST}
  pulsar-subscription-name = "user-events-consumer"
  pulsar-subscription-name = ${?PULSAR_SUBSCRIPTION_NAME}
  pulsar-consumer-topic = "persistent://tenant-a/entity-demo/user-events"   # persistent://tenant/namespace/topic
  pulsar-consumer-topic = ${?CONSUMER_TOPIC}

  temporal-workflow-id-prefix = "user-entity-"
  temporal-workflow-id-prefix = ${?TEMPORAL-WORKFLOW-ID-PREFIX}

  temporal-task-queue = "user-entity-tasks"
  temporal-task-queue = ${?TEMPORAL-TASK-QUEUE}

  cumulative-ack-on-msg-count = 100
  cumulative-ack-on-msg-count = ${?CUMULATIVE_ACK_ON_MSG_COUNT}

  temporal-server-target = "temporal:7233"
  temporal-server-target = ${?TEMPORAL_SERVER_TARGET}

  temporal-server-https-enabled = false
  temporal-server-https-enabled = ${?TEMPORAL_SERVER_HTTPS_ENABLED}

  temporal-prometheus-metrics-port = 8077
  temporal-prometheus-metrics-port = ${?TEMPORAL_PROMETHEUS_METRICS_PORT}
}

negative-acks-dispatcher {  # blocking io dispatcher
  type = Dispatcher
  executor = "thread-pool-executor"
  thread-pool-executor {
    fixed-pool-size = 16
  }
  throughput = 1
}