temporal-server-target=temporal:7233
#temporal-server-target-ip=${?TEMPORAL_SERVER_TARGET}

temporal-server-https-enabled=false
#temporal-server-https-enabled=${?TEMPORAL_SERVER_HTTPS_ENABLED}

temporal-task-queue=user-entity-tasks
#temporal-task-queue=${?TEMPORAL_TASK_QUEUE}

temporal-prometheus-metrics-port=8077
#temporal-prometheus-metrics-port=${?TEMPORAL_PROMETHEUS_METRICS_PORT}

# Duration of 3 Minutes using Duration.parse
user-entity-polling-rate=PT3M
#user-entity-polling-rate=${USER_ENTITY_POLLLING_RATE}