<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>ai.tensor7</groupId>
        <artifactId>entity-demo-parent-java</artifactId>
        <version>0.0.1</version>
    </parent>

    <artifactId>temporal-user-entity-workflow</artifactId>
    <packaging>jar</packaging>

    <name>user-entity-workflow</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>24</maven.compiler.source>
        <maven.compiler.target>24</maven.compiler.target>
        <temporal.sdk.version>1.35.0</temporal.sdk.version>
        <logback.classic.version>1.5.20</logback.classic.version>
        <junit.jupiter.version>5.11.4</junit.jupiter.version>
        <fabric8.maven.plugin.version>0.48.1</fabric8.maven.plugin.version>
<!--        <micrometer-registry-version>1.9.9</micrometer-registry-version>-->
        <micrometer-registry-version>1.16.5</micrometer-registry-version>
        <tests.skip>true</tests.skip>
    </properties>

    <dependencies>

        <dependency>
            <groupId>io.temporal</groupId>
            <artifactId>temporal-sdk</artifactId>
            <version>${temporal.sdk.version}</version>
        </dependency>

<!-- maybe TODO switch to configs by Temporal
        <dependency>
            <groupId>io.temporal</groupId>
            <artifactId>temporal-envconfig</artifactId>
            <version>${temporal.sdk.version}</version>
        </dependency>
-->

        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-prometheus</artifactId>
            <version>${micrometer-registry-version}</version>
        </dependency>

        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-commons</artifactId>
            <version>${micrometer-registry-version}</version>
        </dependency>

        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>${logback.classic.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.19.0</version>
        </dependency>

        <!-- test scope dependencies -->
        <dependency>
            <groupId>io.temporal</groupId>
            <artifactId>temporal-testing</artifactId>
            <version>${temporal.sdk.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>${junit.jupiter.version}</version>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>
        <pluginManagement><!-- lock down plugins versions to avoid using Maven defaults (may be moved to parent pom) -->
            <plugins>
                <!-- clean lifecycle, see https://maven.apache.org/ref/current/maven-core/lifecycles.html#clean_Lifecycle -->
                <plugin>
                    <artifactId>maven-clean-plugin</artifactId>
                    <version>3.1.0</version>
                </plugin>
                <!-- default lifecycle, jar packaging: see https://maven.apache.org/ref/current/maven-core/default-bindings.html#Plugin_bindings_for_jar_packaging -->
                <plugin>
                    <artifactId>maven-resources-plugin</artifactId>
                    <version>3.0.2</version>
                </plugin>
                <plugin>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.8.0</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>3.5.5</version>
                    <configuration>
                        <skipTests>${tests.skip}</skipTests>
                    </configuration>
                </plugin>
                <plugin>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>3.5.0</version>
                </plugin>
                <plugin>
                    <artifactId>maven-install-plugin</artifactId>
                    <version>2.5.2</version>
                </plugin>
                <plugin>
                    <artifactId>maven-deploy-plugin</artifactId>
                    <version>2.8.2</version>
                </plugin>
                <!-- site lifecycle, see https://maven.apache.org/ref/current/maven-core/lifecycles.html#site_Lifecycle -->
                <plugin>
                    <artifactId>maven-site-plugin</artifactId>
                    <version>3.7.1</version>
                </plugin>
                <plugin>
                    <artifactId>maven-project-info-reports-plugin</artifactId>
                    <version>3.0.0</version>
                </plugin>
            </plugins>
        </pluginManagement>

        <plugins>
            <!-- docker image creation -->
            <!-- https://github.com/fabric8io/docker-maven-plugin -->
            <!-- To generate docker image: mvn clean compile package docker:build -->
            <plugin>
                <groupId>io.fabric8</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <version>${fabric8.maven.plugin.version}</version>
                <configuration>
                    <verbose>true</verbose>
                    <useColor>true</useColor>
                    <images>
                        <image>
                            <name>temporal-entity-demo/user-entity</name>
                            <build>
                                <from>docker.io/library/eclipse-temurin:24</from>
                                <tags>
                                    <tag>${project.version}</tag>
                                </tags>
                                <entryPoint>
                                    <exec>
                                        <arg>java</arg>
                                        <arg>-cp</arg>
                                        <arg>/maven/*</arg>
                                        <arg>ai.tensor7.UserEntityWorker</arg>
                                    </exec>
                                </entryPoint>
                                <assemblies>
                                    <assembly>
                                        <descriptorRef>artifact-with-dependencies</descriptorRef>
                                    </assembly>
                                </assemblies>
                            </build>
                        </image>
                    </images>
                </configuration>
                <executions>
                    <execution>
                        <id>build-docker-image</id>
                        <phase>package</phase>
                        <goals>
                            <goal>build</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <!-- END docker image creation -->

        </plugins>
    </build>
</project>
