app {
  pulsar-host = "localhost"
  pulsar-host = ${?PULSAR_HOST}
  pulsar-consumer-topic = "persistent://tenant-a/entity-demo/user-events"   # persistent://tenant/namespace/topic
  pulsar-consumer-topic = ${?PULSAR_CONSUMER_TOPIC}

  batch-size = 300
  batch-wait-milliseconds = 1000
}
